# -*- coding: utf-8 -*-
"""cusap_data_practice.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CMXcB8a_fxx3gz9Z7rNjmuOCu3V2BZDl
"""

import pandas as pd 
from google.colab import files 
import matplotlib.pyplot as plt

uploaded = files.upload()

fruit_dataframe = pd.read_excel("fruit_groups.xlsx")
fruit_dataframe = fruit_dataframe.drop(["Index"], axis = 1)
print(fruit_dataframe)

counted_fruits = fruit_dataframe["Fruit"].value_counts()
counted_fruits.plot.bar()

import requests 
import pandas as pd 

response = requests.get("https://cusap-iot.uc.r.appspot.com/system/listSystems")
response_dict = response.json()

system_dictionary = {
    "System Name":[],
    "System Id":[],
}
print(response_dict["_msg"].keys())

response_dict["_msg"]["payload"][0]
for system in response_dict["_msg"]["payload"]:
  system_dictionary["System Name"].append(system["name"])
  system_dictionary["System Id"].append(system["_id"])

system_dictionary

system_id_dataframe = pd.DataFrame.from_dict(system_dictionary)
system_id_dataframe.to_csv("system_names_to_id.csv")

# First specify your parameters that you want to add in a dictionary
request_params = {
    "systemId": "5f1b2e4df17641001ecfd315",
    "reading": "Air-Humidity",
    "timePeriod": "week"
}

response = requests.get("https://cusap-iot.uc.r.appspot.com/system/getReadings", params=request_params)
print(response.url)